t1 = tuple(["pramod", "dee"])
print(t1)

hero1 = ("Batman", "Bruce  Wayne")
hero2 = ("Wonder women", "Diana Prince")
new_tuple = (hero1,hero2)
print(new_tuple)
print(new_tuple[0])
print(new_tuple[0][0])
print(new_tuple[1][1])